version: "3"
services:
    db:
        image: microsoft/mssql-server-linux
        environment:
            SA_PASSWORD: "Temp2121x"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
